server:
  port: 7777

logging:
  level:
    root: debug
    org.apache.tomcat.util.net.NioEndpoint: error
    sun.rmi: error
    java.io: error
    javax.management: error

spring:
  application:
    name: j-sso
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9b032807837420bc75c9
            clientSecret: 373afe918f624ad1e9b46b331ebb6fdb560a90db
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info